export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const AUTHENTICATION = 'AUTHENTICATION';
export const LOADING = 'LOADING';
export const SET_JOB_DETAILS = 'SET_JOB_DETAILS';
export const EMPLOYER_DETAILS = 'EMPLOYER_DETAILS';